apps/application/urls.py
from django.urls import path

from .views.get_account_view import GetAccountView
from .views.groups_view import GroupsView
from .views.home_view import HomeView
from .views.invitations_view import InvitationsView, CancelInvitationView, ConfirmInvitationView
from .views.invite_player_view import InvitePlayerView
from .views.referred_players_view import ReferredPlayersView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('groups', GroupsView.as_view(), name='groups'),
    path('invitations', InvitationsView.as_view(), name='invitations'),
    path('invitations/confirm-invitation', ConfirmInvitationView.as_view(), name='confirm_invitation'),
    path('invitations/cancel-invitation', CancelInvitationView.as_view(), name='cancel_invitation'),
    path('<game>/get-account', GetAccountView.as_view(), name='get_account'),
    path('<game>/referred-players', ReferredPlayersView.as_view(), name='referred_players'),
    path('<game>/invite-player', InvitePlayerView.as_view(), name='invite_player'),
]

recomteam/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('social-authentication/', include('social_django.urls', namespace="social")),
    path('auth/', include('apps.authentication.urls')),
    path('', include('apps.application.urls')),
]

apps/application/models.py
from uuid import uuid4

from django.contrib.auth.models import User
from django.db import models

from apps.application.games.fortnite import fortnite
from apps.application.games.league_of_legends import lol
from apps.authentication.models import UserProfile


class Statistics(models.Model):
    uuid = models.UUIDField(default=uuid4, editable=False, unique=True)

    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    game_name = models.CharField(max_length=255, blank=False)
    account_name = models.CharField(max_length=255, blank=False)
    points = models.IntegerField(blank=False)
    last_update = models.DateTimeField()

    def update_points(self):
        if self.game_name == "league-of-legends":
            self.points = lol.get_points(self.account_name, "eun1")
        elif self.game_name == "fortnite":
            self.points = fortnite.get_points(self.account_name)
        self.save()


class Group(models.Model):
    uuid = models.UUIDField(default=uuid4, editable=False, unique=True)
    owner = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    game_name = models.CharField(max_length=255)
    created_ad = models.DateTimeField(auto_now_add=True, blank=True)
    is_deleted = models.BooleanField(default=False)


class Invitations(models.Model):
    uuid = models.UUIDField(default=uuid4, editable=False, unique=True)
    user_statistics = models.ForeignKey(Statistics, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)


class GroupRelationships(models.Model):
    uuid = models.UUIDField(default=uuid4, editable=False, unique=True)
    user_statistics = models.ForeignKey(Statistics, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)

apps/application/forms/get_account_form.py
from django import forms


class GetAccountForm(forms.Form):
    account_name = forms.CharField()

apps/application/views/get_account_view.py
import datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.utils import timezone
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.views.generic import FormView

from apps.application.forms.get_account_form import GetAccountForm
from apps.application.games.fortnite import fortnite
from apps.application.games.league_of_legends import lol
from apps.application.models import Statistics


@method_decorator(login_required, name='dispatch')
class GetAccountView(FormView):
    template_name = 'application/get_account.html'
    form_class = GetAccountForm

    def get(self, request, *args, **kwargs):
        try:
            user_statistics = Statistics.objects.get(user=request.user, game_name=kwargs.get('game'))
            return redirect(reverse("referred_players", kwargs={"game": kwargs.get('game')}))
        except Statistics.DoesNotExist:
            pass

        return render(request, self.template_name, {'game': kwargs.get('game')})

    def post(self, request, *args, **kwargs):
        try:
            account_name = request.POST.get("account_name")
            if kwargs.get('game') == 'league-of-legends':
                try:
                    user_statistics = Statistics.objects.get(user=request.user, game_name='league-of-legends')
                except Statistics.DoesNotExist:
                    points = lol.get_points(account_name, "eun1")
                    user_statistics = Statistics(
                        user=request.user,
                        game_name='league-of-legends',
                        account_name=account_name,
                        points=points,
                        last_update=timezone.now())
                    user_statistics.save()

                return redirect(reverse("referred_players", kwargs={"game": "league-of-legends"}))

            elif kwargs.get('game') == 'fortnite':
                try:
                    user_statistics = Statistics.objects.get(user=request.user, game_name='fortnite')
                except Statistics.DoesNotExist:
                    points = fortnite.get_points(account_name)
                    user_statistics = Statistics(
                        user=request.user,
                        game_name='fortnite',
                        account_name=account_name,
                        points=points,
                        last_update=timezone.now())
                    user_statistics.save()

                return redirect(reverse("referred_players", kwargs={"game": "fortnite"}))

        except Exception as e:
            print(str(e))
            messages.error(request, 'Account with this name not exist.')
        return render(request, self.template_name, {'game': kwargs.get('game')})

    def form_valid(self, form):
        return super().form_valid(form)

apps/application/views/groups_view.py
from django.views.generic import ListView

from apps.application.models import Group, Statistics


class GroupsView(ListView):
    model = Group
    template_name = 'application/groups.html'
    context_object_name = 'groups'

    def get_queryset(self):
        user_statistics = Statistics.objects.filter(user=self.request.user)
        return Group.objects.filter(
            grouprelationships__user_statistics__in=user_statistics).exclude(
            owner=self.request.user)

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['your_groups'] = Group.objects.filter(owner=self.request.user)
        return context

apps/application/views/home.py
from django.shortcuts import render
from django.views.generic import View


class HomeView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'application/home.html')

    def post(self, request, *args, **kwargs):
        pass

apps/application/views/home_view.py
from django.shortcuts import render
from django.views.generic import View


class HomeView(View):
    template_name = 'application/home.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        pass

apps/application/views/invitations_view.py
from django.views.generic import ListView

from django.http import JsonResponse
from django.views import View

from apps.application.models import Statistics, Invitations, GroupRelationships


class InvitationsView(ListView):
    model = Invitations
    template_name = 'application/invitations.html'
    context_object_name = 'invitations'

    def get_queryset(self):
        user_statistics = Statistics.objects.filter(user=self.request.user)
        return Invitations.objects.filter(user_statistics__in=user_statistics)


class ConfirmInvitationView(View):
    def post(self, request, *args, **kwargs):
        uuid = request.POST.get('id', None)
        if uuid:
            try:
                invitation = Invitations.objects.get(uuid=uuid)
                group = invitation.group

                group_relationship = GroupRelationships(user_statistics=invitation.user_statistics, group=group)
                group_relationship.save()

                invitation.delete()
                return JsonResponse(data={
                    "message": "Dołączyłeś do grupy użytkownika {} w grze: {}".format(
                        group.owner, group.game_name)
                })
            except Invitations.DoesNotExist:
                pass

        return JsonResponse(data={"message": "Coś poszło nie tak"})


class CancelInvitationView(View):
    def post(self, request, *args, **kwargs):
        uuid = request.POST.get('id', None)
        if uuid:
            try:
                invitation = Invitations.objects.get(uuid=uuid)
                group = invitation.group

                invitation.delete()
                return JsonResponse(data={
                    "message": "Anulowałeś zaproszenie do grupy użytkownika {} w grze: {}".format(
                        group.owner, group.game_name)
                })
            except Invitations.DoesNotExist:
                pass

        return JsonResponse(data={"message": "Coś poszło nie tak"})

apps/application/views/invite_player_view.py
from django.http import JsonResponse
from django.views import View

from apps.application.models import Statistics, Invitations, Group, GroupRelationships


class InvitePlayerView(View):
    def post(self, request, *args, **kwargs):
        uuid = request.POST.get('id', None)

        game_name = kwargs.get('game')
        user = request.user
        if uuid:
            try:
                statistics = Statistics.objects.get(uuid=uuid)
                your_statistics = Statistics.objects.get(user=user, game_name=game_name)
                try:
                    group = Group.objects.get(owner=user, game_name=game_name)
                except Group.DoesNotExist:
                    group = Group(game_name=game_name, owner=user)
                    group.save()
                    group_relationships = GroupRelationships(group=group, user_statistics=your_statistics)
                    group_relationships.save()

                invitation = Invitations(group=group, user_statistics=statistics)
                invitation.save()
                return JsonResponse(data={
                    "message": "Zaprosiłeś użytkownika {} do swojej grupy w grze: {}".format(
                        statistics.account_name, game_name)
                })
            except Statistics.DoesNotExist:
                pass

        return JsonResponse(data={"message": "Coś poszło nie tak"})

apps/application/views/referred_players_view.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import View

from apps.application.models import Statistics, Group, Invitations, GroupRelationships


@method_decorator(login_required, name='dispatch')
class ReferredPlayersView(View):
    template_name = 'application/referred_players.html'

    def get(self, request, *args, **kwargs):
        try:
            your_statistics = Statistics.objects.get(user=request.user, game_name=kwargs.get('game'))
        except Statistics.DoesNotExist:
            return redirect(reverse("get_account", kwargs={"game": kwargs.get('game')}))
        groups = Group.objects.filter(owner=request.user, game_name=kwargs.get('game'))

        statistics_of_other_players = list(Statistics.objects.exclude(
            user=request.user).exclude(
            invitations__group__in=groups).exclude(
            grouprelationships__group__in=groups).filter(
            game_name=kwargs.get('game')
            ).values())
        if statistics_of_other_players:
            statistics_of_other_players = recommendation_algorithm_the_best_first(
                your_statistics.points, statistics_of_other_players)

        return render(request, self.template_name, {'game': kwargs.get('game'),
                                                    'your_statistics': your_statistics,
                                                    "statistics_of_other_players": statistics_of_other_players})

    def post(self, request, *args, **kwargs):
        try:
            your_statistics = Statistics.objects.get(user=request.user, game_name=kwargs.get('game'))
        except Statistics.DoesNotExist:
            return redirect(reverse("get_account", kwargs={"game": kwargs.get('game')}))

        your_statistics.update_points()

        groups = Group.objects.filter(owner=request.user, game_name=kwargs.get('game'))

        statistics_of_other_players = list(Statistics.objects.exclude(
            user=request.user).exclude(
            invitations__group__in=groups).exclude(
            grouprelationships__group__in=groups).filter(
            game_name=kwargs.get('game')
        ).values())
        if statistics_of_other_players:
            statistics_of_other_players = recommendation_algorithm_the_best_first(
                your_statistics.points, statistics_of_other_players)

        return render(request, self.template_name, {'game': kwargs.get('game'),
                                                    'your_statistics': your_statistics,
                                                    "statistics_of_other_players": statistics_of_other_players})



def recommendation_algorithm_the_best_first(your_points, statistics_of_other_players):
    sorted_best_first_statistics_of_other_players = []
    while len(statistics_of_other_players):
        best_player_statistics = __best_first(your_points, statistics_of_other_players)
        sorted_best_first_statistics_of_other_players.append(best_player_statistics)
        statistics_of_other_players.remove(best_player_statistics)

    return sorted_best_first_statistics_of_other_players


def __best_first(your_points, statistics_of_other_players):
    best_player_statistics = None

    for player_statistics in statistics_of_other_players:
        best_player_statistics = __return_better_statistics(your_points, player_statistics, best_player_statistics)

    return best_player_statistics


def __return_better_statistics(your_points, player_statistics, best_player_statistics):
    if best_player_statistics:
        if abs(your_points - player_statistics.get("points")) > abs(your_points - best_player_statistics.get("points")):
            return best_player_statistics
        return player_statistics
    else:
        return player_statistics

templates/application/get_account.html
{% extends 'base_layout.html' %}
{% load static %}



{% block title %}  {% endblock %}

{% block content %}
    <div class="container get-account-container">
        <div class="row justify-content-md-center d-flex align-items-center">
            <div class="col-md-4 col-sm-12">
                <div class="row">
                    {% if game == 'league-of-legends' %}
                        <img class="game-logo" src="{% static 'img/league_of_legends_logo.png' %}">
                    {% elif game == 'valorant' %}
                        <img class="game-logo" src="{% static 'img/valorant_logo.png' %}">
                    {% elif game == 'fortnite' %}
                        <img class="game-logo" src="{% static 'img/fortnite_logo.png' %}">
                    {% endif %}
                </div>
                <div class="row">
                    <div class="col-12">
                        <form method="post" class="form-game-account">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="gameAccountName">Nazwa gracza</label>
                                <input type="text" id="gameAccountName" class="form-control"
                                       name="account_name" placeholder="Nazwa gracza" required
                                       autofocus>
                            </div>
                            <div class="mb-5">
                                <button class="btn btn-lg btn-primary btn-block" type="submit">Dodaj</button>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/application/groups.html
{% extends 'base_layout.html' %}
{% load static %}


{% block title %}  {% endblock %}

{% block content %}

    <div class="container container-group">
        {% for group in your_groups %}
            <div class="my-3 p-3 bg-dark rounded shadow-sm group-card" id="{{ group.uuid }}">
                {% if group.game_name == 'league-of-legends' %}
                    <img class="game-logo" style="width: 25%;" src="{% static 'img/league_of_legends_logo.png' %}">
                {% elif group.game_name == 'valorant' %}
                    <img class="game-logo" style="width: 25%;" src="{% static 'img/valorant_logo.png' %}">
                {% elif group.game_name == 'fortnite' %}
                    <img class="game-logo" src="{% static 'img/fortnite_logo.png' %}">
                {% endif %}
                <h4 class="border-bottom pb-2 mb-0">Właściciel: Ty</h4>
                <div class="d-flex text-muted pt-3">
                    <div class="pb-3 mb-0 small lh-sm w-100">
                        {% for relationship in group.grouprelationships_set.all %}
                            <div class="d-flex justify-content-between">
                                <div>
                                    <h6>
                                        <strong>{{ relationship.user_statistics.account_name }}</strong>
                                    </h6>
                                </div>
                                <div>
                                    <h6>
                                        Punkty: {{ relationship.user_statistics.points }}
                                    </h6>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endfor %}
        {% for group in groups %}
            <div class="my-3 p-3 bg-dark rounded shadow-sm group-card" id="{{ group.uuid }}">
                {% if group.game_name == 'league-of-legends' %}
                    <img class="game-logo" style="width: 25%;" src="{% static 'img/league_of_legends_logo.png' %}">
                {% elif group.game_name == 'valorant' %}
                    <img class="game-logo" style="width: 25%;" src="{% static 'img/valorant_logo.png' %}">
                {% elif group.game_name == 'fortnite' %}
                    <img class="game-logo" src="{% static 'img/fortnite_logo.png' %}">
                {% endif %}
                <h4 class="border-bottom pb-2 mb-0">Właściciel: {{ group.owner }}</h4>
                <div class="d-flex text-muted pt-3">
                    <div class="pb-3 mb-0 small lh-sm w-100">
                        {% for relationship in group.grouprelationships_set.all %}
                            <div class="d-flex justify-content-between">
                                <div>
                                    <h6>
                                        <strong>{{ relationship.user_statistics.account_name }}</strong>
                                    </h6>
                                </div>
                                <div>
                                    <h6>
                                        Punkty: {{ relationship.user_statistics.points }}
                                    </h6>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/application/home.html
{% extends 'base_layout.html' %}
{% load static %}
<!-- templates/application/home.html -->


{% block title %} Home page {% endblock %}

{% block content %}
    <div class="container home-container">
        <div class="row">
            <div class="col-md-6 col-sm-1  justify-content-center  d-flex align-items-center">
                <a href="{% url 'get_account' game='league-of-legends' %}">
                    <img class="game-logo" src="{% static 'img/league_of_legends_logo.png' %}">
                </a>
            </div>
            {#            <div class="col-md-6 col-sm-1  justify-content-center  d-flex align-items-center">#}
            {#                <a href="{% url 'get_account' game='valorant' %}">#}
            {#                    <img class="game-logo" src="{% static 'img/valorant_logo.png' %}">#}
            {#                </a>#}
            {#            </div>#}
            <div class="col-md-6 col-sm-1  justify-content-center  d-flex align-items-center">
                <a href="{% url 'get_account' game='fortnite' %}">
                    <img class="game-logo" src="{% static 'img/fortnite_logo.png' %}">
                </a>
            </div>
        </div>
    </div>
{% endblock %}

templates/application/invitations.html
{% extends 'base_layout.html' %}
{% load static %}


{% block title %}  {% endblock %}

{% block content %}

    <div class="container">
        {% for invitation in invitations %}
            <div class="my-3 p-3 bg-dark rounded shadow-sm" id="invitationId{{ invitation.uuid }}">
                {% if invitation.group.game_name == 'league-of-legends' %}
                    <img class="game-logo" style="width: 25%;" src="{% static 'img/league_of_legends_logo.png' %}">
                {% elif invitation.group.game_name == 'valorant' %}
                    <img class="game-logo" style="width: 25%;" src="{% static 'img/valorant_logo.png' %}">
                {% elif invitation.group.game_name == 'fortnite' %}
                    <img class="game-logo" style="width: 25%;" src="{% static 'img/fortnite_logo.png' %}">
                {% endif %}
                <h4 class="border-bottom pb-2 mb-0">Zaproszenie do grupy</h4>
                <div class="d-flex text-muted pt-3">
                    <div class="pb-3 mb-0 small lh-sm w-100">
                        <div class="d-flex justify-content-between">
                            <div>
                                <h6>
                                    Od: <strong>{{ invitation.group.owner }}</strong>
                                </h6>
                            </div>
                            <div>
                                <button type="button" class="btn btn-primary confirm-invitation"
                                        id="{{ invitation.uuid }}">Akceptuj
                                </button>
                                <button type="button" class="btn btn-secondary cancel-invitation"
                                        id="{{ invitation.uuid }}">Odrzuć
                                </button>
                            </div>

                        </div>
                        <span class="d-block">
                            <h6>
                                Gra: <strong>{{ invitation.group.game_name }}</strong>
                            </h6>
                        </span>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/application/referred_players.html
{% extends 'base_layout.html' %}
{% load static %}

{% block title %}  {% endblock %}

{% block content %}
    <div class="container referred-players-container">
        <div class="row">
            <div class="col-md-4 col-sm-12">
                {% if game == 'league-of-legends' %}
                    <img class="game-logo" src="{% static 'img/league_of_legends_logo.png' %}">
                {% elif game == 'valorant' %}
                    <img class="game-logo" src="{% static 'img/valorant_logo.png' %}">
                {% elif game == 'fortnite' %}
                    <img class="game-logo" src="{% static 'img/fortnite_logo.png' %}">
                {% endif %}
            </div>
            <div class="col-md-4 offset-md-4 col-sm-12 justify-content-center">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ your_statistics.account_name }}</h5>
                        <p class="card-text">
                            <b>Twoje punkty: {{ your_statistics.points }}</b>
                        </p>
                        <form class="form-update" method="post">
                            {% csrf_token %}
                            <button type=submit class="btn btn-success">
                                Aktualizuj punkty
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            {% for player_statistics in statistics_of_other_players %}
                <div class="col-md-4 col-sm-12 " id="playerStatisticsId{{ player_statistics.uuid }}">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">{{ player_statistics.account_name }}</h5>
                            <p class="card-text">
                                <b>Punkty: {{ player_statistics.points }}</b>
                            </p>
                            <a class="btn btn-primary invite-player-button" id="{{ player_statistics.uuid }}">Zaproś
                                gracza do grupy</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}